### ISSUE TITLE
Visualization video

### ISSUE THREAD

**Issue by Xjunjiang** [MCG-NJU/BCN#2]
Hello. Thank you so much for the files and code you uploaded, and we want to see the "Visualization video" in real scene. Can you provide this part of the code?

**Comment by zhenzhiwang** [comment]
Hi Xjunjiang,

Thank you for your interest in our paper. The authors are busy recently therefore may not be able to finish the visualization codes. However, for coarse-level visualizations such as Figure.6 in the paper, we can share codes and output results for GTEA and 50salads datasets (not including the breakfast dataset due to the large file size of output results). We welcome your contributions ( e.g., pull requests) of per-frame action label visualizations attached in the original videos using the gt and output results of our model.

For any other questions, feel free to comment here or send emails to us.
