### ISSUE TITLE
split problem

### ISSUE THREAD

**Issue by Felix1014** [MCG-NJU/BCN#3]
Dear authors，

What is the meaning of split?  There are many _**.bundle files**_ in the /data/split, and can you explain this? Thank you!

**Comment by zhenzhiwang** [comment]
The setting of splits in the datasets follows the usage of cross-validation in the machine learning community, where we separate the dataset into "N" parts and use "N-1" parts as the training set and the last part as the testing set. The above process will be repeated in "N" times with different split as the testing set so that the methods can be evaluated in each split. The datasets in temporal action segmentation are proposed between 2011-2014 and their data scales are limited, so commonly the authors in this area use cross-validation as a standard evaluation protocol, including me.

As for .bundle files in the /data/split, the author of MS-TCN (https://github.com/yabufarha/ms-tcn) uses them to save the id of the training/test samples, e.g., "rgb-01-1.txt" in 50Salads, and I directly use it in my experiments.
